args:
  api_key: sk-jwebxbzbipkkcaekohbvqefknpnljinkrxfwkkvajmzvfvbx
  api_url: https://api.siliconflow.cn/v1/chat/completions
  batch_size: 1
  datasets:
  - LexEval
  json_inputs: {}
  max_tokens: 4096
  models:
  - api:Qwen/Qwen3-8B
  num_workers: 4
  repetition_penalty: 1
  retrieval_method: none
  sub_tasks:
  - '1_1'
  task: all
  temperature: 0.7
  tensor_parallel: 1
  top_p: 0.9
